name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.platform.runner }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform:
          - name: macOS
            runner: macos-latest
            artifact_name: crow-video-macos
            artifact_paths: |
              release/*.dmg
          - name: Windows
            runner: windows-latest
            artifact_name: crow-video-windows
            artifact_paths: |
              release/*-setup.exe

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.17.0'

      - name: Install Dependencies
        run: |
          npm install -g pnpm@10.12.4
          pnpm install

      - name: Build MacOS
        if: matrix.platform.name == 'macOS'
        run: |
          export ELECTRON_BUILDER_EXTRA_ARGS="--universal"
          pnpm run lipo-ffmpeg
          pnpm run build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_IDENTITY_AUTO_DISCOVERY: false

      - name: Build Windows
        if: matrix.platform.name == 'Windows'
        run: pnpm run build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform.artifact_name }}-${{ github.sha }}
          if-no-files-found: error
          path: ${{ matrix.platform.artifact_paths }}

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: .
          pattern: crow-video-*
          merge-multiple: true

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.dmg
            *-setup.exe
