name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.17.0'

      - name: Install Dependencies
        run: |
          npm install -g pnpm@10.12.4
          pnpm install

      - name: Build MacOS
        run: |
          export ELECTRON_BUILDER_EXTRA_ARGS="--universal"
          pnpm run lipo-ffmpeg
          pnpm run build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_IDENTITY_AUTO_DISCOVERY: false
          DEBUG: electron-builder

      - name: Upload Mac artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: release/**/*.dmg

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.17.0'

      - name: Install Dependencies
        run: |
          npm install -g pnpm@10.12.4
          pnpm install

      - name: Build Windows
        run: pnpm run build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: release/**/*.exe

  release:
    needs: [build-macos, build-windows]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Download Mac artifact
        uses: actions/download-artifact@v4
        with:
          name: macos-build
          path: .

      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-build
          path: .

      - name: List files
        run: find . -name "*.dmg" -o -name "*.exe"

      - name: Upload artifacts to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release/**/*.dmg
            release/**/*.exe
